import { createSlice } from "@reduxjs/toolkit";

type Todo = {
  id: string;
  text: string;
};

const initialState: { todos: Todo[] } = {
  todos: [],
};

// slice ma chai Redux ko logic lekhinxa. createSlice le object linxa
// A slice contains: name, initial state, and reducer logic

// Also we need to Export the reducer function
// This is used in store.ts when configuring the Redux store
export const todoSlice = createSlice({
  name: "todo",
  initialState,
  //reducers vitra actions hunxa
  reducers: {
    // Action to add a new todo
    addTodo: (state, action) => {
      state.todos.push({ id: Math.random().toString(), text: action.payload });
    },
  },
});

// Export the action creator generated by createSlice
// Used in components with dispatch(addTodo("text"))
export const { addTodo } = todoSlice.actions;
